fileVersion: 1
id: "25"
mappingDefinitions:
  HEE:
    database: COALESCE_DEV
    schema: dbo
  TEST:
    database: COALESCE_DEV
    schema: shruthi_test
name: New Environment -Fabric
type: Environment
